"""Guard mutation check — proves the security tests would notice a guard's removal.

    python tests/tools/guard_mutations.py            # every mutant
    python tests/tools/guard_mutations.py M01 M07    # a selection
    python tests/tools/guard_mutations.py --list

Each mutant disables exactly one deterministic guard with one exact source edit
(the "old" text must occur exactly once, or the mutant refuses to run), runs the
test selection that is supposed to defend that guard, and **expects it to
fail**. A mutant whose tests still pass is a *survivor*: the guard could be
deleted and nothing would notice. The file is restored byte-for-byte in a
`finally`, whatever happens.

This is Phase H's §21 evidence (docs/RELEASE_VALIDATION.md records the last
run). It is not wired into CI — a full run re-executes large suites once per
mutant — but `tests/foundation/test_guard_mutations_meta.py` keeps every
mutant's anchor text present, so the catalogue cannot silently rot as the code
moves.
"""

from __future__ import annotations

import os
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PY = [sys.executable, "-m", "pytest", "-x", "-q", "-p", "no:cacheprovider", "-p", "no:logging", "-W", "ignore"]
GRADLE = ["./gradlew", "--offline", "-q", ":contract:test"]


@dataclass(frozen=True)
class Mutant:
    id: str
    guard: str
    path: str
    old: str
    new: str
    command: tuple[str, ...]
    cwd: str = "."


MUTANTS: tuple[Mutant, ...] = (
    Mutant("M01", "AuthZ D4 visibility: a private resource becomes readable by anyone who reaches it",
           "server/graph/predicate.py",
           "        and is_active_member_of_resource_graph\n    ):\n        return True\n    return False",
           "        and is_active_member_of_resource_graph\n    ):\n        return True\n    return True",
           (*PY, "tests/security_core/test_authorization.py")),
    Mutant("M02", "AuthZ D4 graph scope: graph_id alone authorizes (membership ignored)",
           "server/graph/predicate.py",
           "        and is_active_member_of_resource_graph\n    ):",
           "        and True\n    ):",
           (*PY, "tests/security_core/test_authorization.py")),
    Mutant("M03", "AuthZ D1 membership: a non-member passes the graph check",
           "server/graph/authorization.py",
           "            if role is None:\n                return _deny(\"not_a_member\", DenialSurface.NOT_FOUND)",
           "            if False:\n                return _deny(\"not_a_member\", DenialSurface.NOT_FOUND)",
           (*PY, "tests/security_core/test_authorization.py")),
    Mutant("M04", "Confirmation: the token no longer binds the exact arguments",
           "server/capabilities/confirmation.py",
           "        and row.arguments_hash == binding.arguments_hash()",
           "        and True",
           (*PY, "tests/security_core/test_confirmation.py")),
    Mutant("M05", "Confirmation: the token no longer binds the session",
           "server/capabilities/confirmation.py",
           "        and row.session_id == binding.session_id",
           "        and True",
           (*PY, "tests/security_core/test_confirmation.py")),
    Mutant("M06", "Step-up: a bad signature is accepted",
           "server/auth/step_up.py",
           "            except (InvalidSignature, ValueError, binascii.Error):\n                reason = \"bad_signature\"",
           "            except (InvalidSignature, ValueError, binascii.Error):\n                reason = None",
           (*PY, "tests/security_core/test_step_up.py")),
    Mutant("M07", "Step-up: an expired challenge is accepted",
           "server/auth/step_up.py",
           "        elif expires_at is None or now >= as_utc(expires_at):",
           "        elif False:",
           (*PY, "tests/security_core/test_step_up.py")),
    Mutant("M08", "Device routing: an operation goes to any connected device, not its exact device_id",
           "server/execution/device_hub.py",
           "        session = self._sessions.get(operation.device_id)\n        if session is None:\n"
           "            # Never queued.",
           "        session = next(iter(self._sessions.values()), None)\n        if session is None:\n"
           "            # Never queued.",
           (*PY, "tests/execution/test_device_hub.py")),
    Mutant("M09", "Absolute floor: a reserved capability name is no longer recognised",
           "server/capabilities/floor.py",
           "    normalized = capability.strip().lower()\n    if normalized in _RESERVED_CAPABILITY_NAMES:",
           "    normalized = capability.strip().lower()\n    return None\n    if normalized in _RESERVED_CAPABILITY_NAMES:",
           (*PY, "tests/security_core/test_capabilities.py", "tests/security_core/test_confirmation.py")),
    Mutant("M10", "SecretStore: the agent requester may resolve a secret",
           "server/secrets/store.py",
           "        # contract stopping server.agent from importing this package).\n"
           "        if requester.kind is RequesterKind.AGENT:",
           "        # contract stopping server.agent from importing this package).\n"
           "        if False:",
           (*PY, "tests/security_core/test_secretstore.py")),
    Mutant("M11", "Secret filter: nothing is ever detected as a secret",
           "server/security/secret_patterns.py",
           '    """The name of the first secret pattern `text` matches, else `None`."""\n',
           '    """The name of the first secret pattern `text` matches, else `None`."""\n    return None\n',
           (*PY, "tests/memory/test_write_gate.py")),
    Mutant("M12", "Egress: the cloud metadata address is no longer blocked",
           "server/net/policy.py",
           "    if str(parsed) in _METADATA_ADDRESSES or address_text in _METADATA_ADDRESSES:",
           "    if False:",
           (*PY, "tests/execution/test_net_egress.py")),
    Mutant("M13", "Egress: loopback is no longer blocked",
           "server/net/policy.py",
           "    if parsed.is_loopback:",
           "    if False:",
           (*PY, "tests/execution/test_net_egress.py")),
    Mutant("M14", "Sandbox: a read/listing follows a symlink swapped in after the check (TOCTOU)",
           "server/fs/sandbox.py",
           "        return os.open(name, flags | os.O_NOFOLLOW, dir_fd=dir_fd)",
           "        return os.open(name, flags, dir_fd=dir_fd)",
           (*PY, "tests/execution/test_fs_sandbox.py")),
    Mutant("M27", "Sandbox: a write follows a symlink at the leaf",
           "server/fs/sandbox.py",
           "            flags = os.O_WRONLY | os.O_NOFOLLOW | (os.O_CREAT",
           "            flags = os.O_WRONLY | (os.O_CREAT",
           (*PY, "tests/execution/test_fs_sandbox.py")),
    Mutant("M15", "Resource scope: an unclassified app may be UI-controlled",
           "server/capabilities/app_classification.py",
           "            return ScopeConstraint(denial=APP_NOT_CLASSIFIED)",
           "            return ScopeConstraint()",
           (*PY, "tests/runtime/test_sensitive_app_gate.py")),
    Mutant("M16", "Principal freshness: a revoked device's task keeps running",
           "server/composition/security_port.py",
           "        if device is None or device.revoked or device.user_id != principal.user_id:\n"
           "            return False\n        # The same link",
           "        if device is None or device.user_id != principal.user_id:\n"
           "            return False\n        # The same link",
           (*PY, "tests/runtime/test_platform_wait.py", "tests/runtime/test_lifecycle_and_blast_radius.py")),
    Mutant("M17", "Break-glass: activation no longer requires a verified superuser",
           "server/composition/break_glass.py",
           "    if not isinstance(principal, SuperuserPrincipal) or not principal.grant.is_valid():",
           "    if False:",
           (*PY, "tests/security_core/test_break_glass_registry.py")),
    Mutant("M18", "Mode ceiling: draft/suggest/observe tasks may execute above low_read",
           "server/agent/runtime.py",
           "        if modes.MODE_CEILING[state.mode] is None:\n            return True",
           "        if True:\n            return True",
           (*PY, "tests/runtime/test_task_modes.py")),
    Mutant("M19", "Memory hydration: the engine's readable() re-check is skipped",
           "server/memory/hydration.py",
           "            if not readable(",
           "            if False and not readable(",
           (*PY, "tests/runtime/test_memory_hydration.py")),
    Mutant("M20", "Idempotency: keys are no longer namespaced by user (cross-user replay)",
           "server/gateway/routers/agent.py",
           '            idempotency_key=f"{principal.user_id}:{idempotency_key}",\n'
           '            method="POST",\n            path="/api/v1/agent/tasks",',
           '            idempotency_key=idempotency_key,\n'
           '            method="POST",\n            path="/api/v1/agent/tasks",',
           (*PY, "tests/runtime/test_resource_control.py")),
    Mutant("M21", "Push: the wake payload carries a task id",
           "shared/schemas/push.py",
           '            "data": WakeData().model_dump(),',
           '            "data": {**WakeData().model_dump(), "task_id": "t-1"},',
           (*PY, "tests/security_core/test_push_wake.py")),
    Mutant("M22", "Voice: a speaker context may claim to be an authorization signal",
           "shared/schemas/voice.py",
           "    is_authorization_signal: Literal[False] = False",
           "    is_authorization_signal: bool = False",
           (*PY, "tests/voice/test_voice_privacy_and_authority.py", "tests/foundation/test_schemas.py")),
    Mutant("M23", "Scheduler: the firing path imports the agent runtime (a path to execution)",
           "server/scheduler/firing.py",
           "from __future__ import annotations\n",
           "from __future__ import annotations\n\nimport server.agent.runtime  # noqa: F401 — mutant\n",
           ("lint-imports", "--config", "pyproject.toml")),
    Mutant("M24", "Device guard (Kotlin): a toggled-off app is no longer refused on the phone",
           "android/contract/src/main/kotlin/com/hypermind/jarvis/contract/DeviceGuard.kt",
           "        if (!toggleOn) return GuardVerdict.Refused(RefusalReason.TOGGLE_OFF)",
           "        if (false) return GuardVerdict.Refused(RefusalReason.TOGGLE_OFF)",
           tuple(GRADLE), cwd="android"),
    Mutant("M25", "Device guard (Kotlin): an expired operation runs",
           "android/contract/src/main/kotlin/com/hypermind/jarvis/contract/DeviceGuard.kt",
           "            !now.isBefore(expires) -> RefusalReason.OPERATION_EXPIRED",
           "            false -> RefusalReason.OPERATION_EXPIRED",
           tuple(GRADLE), cwd="android"),
    Mutant("M26", "Device guard (Kotlin): an operation addressed to another device runs",
           "android/contract/src/main/kotlin/com/hypermind/jarvis/contract/DeviceGuard.kt",
           "        if (envelope.deviceId != deviceId) return RefusalReason.WRONG_DEVICE",
           "        if (false) return RefusalReason.WRONG_DEVICE",
           tuple(GRADLE), cwd="android"),
    # ── Real-data gate: Stage 5 surfaces and grant scoping ──────────────
    Mutant("M28", "Console (DSH-T4): user content is shown instead of redacted",
           "server/dashboard/redaction.py",
           '    return {"redacted": True, "chars": len(text)}',
           "    return text",
           (*PY, "tests/dashboard/test_console.py")),
    Mutant("M29", "Console (DSH-T3): a credential inside a setting is no longer masked",
           "server/dashboard/redaction.py",
           "    return redact_secrets(text)[0]",
           "    return text",
           (*PY, "tests/dashboard/test_console.py")),
    Mutant("M30", "Console (DSH-T4): the unredacted view is no longer audited before it reads",
           "server/gateway/routers/admin.py",
           "    await audit.record(actor=AuditActor.SUPERUSER, action=AuditAction.CONSOLE_UNREDACTED_VIEW,",
           "    False and await audit.record(actor=AuditActor.SUPERUSER, action=AuditAction.CONSOLE_UNREDACTED_VIEW,",
           (*PY, "tests/dashboard/test_console.py")),
    Mutant("M31", "Console (DSH-T2): a console view no longer requires the superuser principal",
           "server/gateway/routers/admin.py",
           "async def banner(request: Request, _: SuperuserPrincipal = Depends(get_superuser),",
           "async def banner(request: Request,",
           (*PY, "tests/dashboard/test_console.py")),
    Mutant("M32", "Judge (JDG-B2): a post-hoc evaluation may stop a task",
           "server/evaluation/service.py",
           "        if kind is not EvaluationKind.LIVE_WINDOW:",
           "        if False:",
           (*PY, "tests/evaluation/test_service.py")),
    Mutant("M33", "Judge (JDG-B2): a stop is honoured while the operator's stop switch is off",
           "server/evaluation/service.py",
           "        if self._breaker is None or not self._switches.stop_requests_enabled():",
           "        if self._breaker is None:",
           (*PY, "tests/evaluation/test_service.py")),
    Mutant("M34", "Judge (JDG-T6): a secret in the trace reaches the Judge unredacted",
           "server/evaluation/trace.py",
           "        clean, names = redact_secrets(text)",
           "        clean, names = text, []",
           (*PY, "tests/evaluation/test_judge_contract.py")),
    Mutant("M35", "Judge (JDG-T7): a candidate may cite another task (another user's) as evidence",
           "server/evaluation/candidates.py",
           "    if any(e != task_id for e in evidence):",
           "    if False:",
           (*PY, "tests/evaluation/test_judge_contract.py")),
    Mutant("M36", "Judge (JDG-T9): an improvement decision no longer requires a verified superuser",
           "server/composition/improvements.py",
           "    if not isinstance(principal, SuperuserPrincipal) or not principal.grant.is_valid():",
           "    if False:",
           (*PY, "tests/evaluation/test_improvements.py")),
    Mutant("M37", "Judge (JDG-T8): the Judge's own budget no longer refuses a paid call",
           "server/evaluation/service.py",
           "            if spent + projected_cost > self._settings.budget:",
           "            if False:",
           (*PY, "tests/evaluation/test_service.py", "tests/evaluation/test_judge_runtime.py")),
    Mutant("M38", "Judge (JDG-B4): the operator can switch on stop requests the config withholds",
           "server/composition/improvements.py",
           "        if stop_requests_enabled and not (config.enabled and config.may_request_stop):",
           "        if False:",
           (*PY, "tests/evaluation/test_improvements.py")),
    Mutant("M39", "AuthZ D5 capability: a request without the required grant passes",
           "server/graph/authorization.py",
           "            if not granted:\n                return _deny(\"capability_missing\", DenialSurface.FORBIDDEN)",
           "            if False:\n                return _deny(\"capability_missing\", DenialSurface.FORBIDDEN)",
           (*PY, "tests/runtime/test_authorization_and_capabilities.py")),
    Mutant("M40", "Task-scoped grant: usable by a principal other than the user who consented",
           "server/capabilities/grants.py",
           "            and row.granted_by == context.principal.user_id",
           "            and True",
           (*PY, "tests/security_core/test_runtime_security_extensions.py", "tests/security_core/test_capabilities.py",
            "tests/runtime/test_authorization_and_capabilities.py")),
    Mutant("M41", "Device-scoped grant (per-app grid): matches any device",
           "server/capabilities/grants.py",
           "        return row.principal_id == context.principal.device_id",
           "        return True",
           (*PY, "tests/security_core/test_grid_grants.py", "tests/security_core/test_capabilities.py")),
    # H-1: the guards that concurrent requests on a multi-writer store need.
    # Run them with HYPERMIND_TEST_DATABASE_URL set, as CI's `postgres` job does.
    Mutant("M42", "H-1 idempotency: a same-key retry while the original runs executes again",
           "server/storage/idempotency.py",
           "    if idempotency_key in _IN_FLIGHT:",
           "    if False:",
           (*PY, "tests/runtime/test_concurrent_store.py")),
    Mutant("M43", "H-1 usage admission: calls admitted but not yet in the ledger stop counting",
           "server/security/usage.py",
           "        return [a for a in self._admitted.values() if a.recorded_in is not own]",
           "        return []",
           (*PY, "tests/runtime/test_concurrent_store.py")),
    Mutant("M44", "H-1 transaction scope: a task's store transaction is held across its model and tool calls",
           "server/agent/runtime.py",
           "    if env.release_store is not None:\n        await env.release_store()",
           "    return None",
           (*PY, "tests/runtime/test_concurrent_store.py")),
    # ── docs/29 Agent Factory (M-AG*) ────────────────────────────────────
    Mutant("M-AG1", "Agent drafts: unknown fields (owner, graph, capability, tier, secret...) are ignored instead of rejected",
           "shared/schemas/agent_factory.py",
           '    model_config = ConfigDict(extra="forbid", frozen=True)',
           '    model_config = ConfigDict(extra="ignore", frozen=True)',
           (*PY, "tests/agents/test_schemas.py")),
    Mutant("M-AG2", "Agent envelope gate: every call is admitted (the ceiling no longer removes anything)",
           "server/agent/envelope.py",
           "    return any(\n        entry.capability == capability and operation in entry.operations",
           "    return True or any(\n        entry.capability == capability and operation in entry.operations",
           (*PY, "tests/agents/test_future_interfaces.py", "tests/agents/test_envelope_gate.py")),
    Mutant("M-AG15", "Native provider: a foreign runtime's handle is acted on as if it were native",
           "server/agents/providers/native.py",
           "    if runtime_id != NATIVE_RUNTIME_ID:\n        raise ValueError",
           "    if False:\n        raise ValueError",
           (*PY, "tests/agents/test_native_provider.py")),
    Mutant("M-AG16", "Agent run: a deleted, paused or revoked definition no longer stops its running run",
           "server/agents/service.py",
           "        if spec is None or definition.status != AgentStatus.ACTIVE.value:\n            return AgentFailureCode.AGENT_UNAVAILABLE\n        if definition.owner_user_id",
           "        if False:\n            return AgentFailureCode.AGENT_UNAVAILABLE\n        if definition.owner_user_id",
           (*PY, "tests/agents/test_agent_runs.py")),
    Mutant("M-AG17", "Agent run: a run keeps going on a spec version/hash the owner has since replaced",
           "server/agents/service.py",
           "        if definition.current_version != version or spec.spec_hash != spec_hash:\n",
           "        if False:\n",
           (*PY, "tests/agents/test_agent_runs.py")),
    Mutant("M-AG18", "Agent run: the runtime stops re-validating the definition at each step",
           "server/agent/runtime.py",
           "        code = await env.agent_runs.check(state.agent)\n",
           "        code = None\n",
           (*PY, "tests/agents/test_agent_runs.py", "tests/agents/test_gateway_runs.py")),
    Mutant("M-AG19", "Agent run: an agent runs outside its own graph",
           "server/composition/agents.py",
           "        if spec.graph_id != graph_id:\n",
           "        if False:\n",
           (*PY, "tests/agents/test_agent_runs.py")),
    Mutant("M-AG20", "Agent run: an agent that is not active (needs re-approval, paused) can start a run",
           "server/composition/agents.py",
           "        if definition.status != AgentStatus.ACTIVE.value:\n            raise await self._refuse_run(",
           "        if False:\n            raise await self._refuse_run(",
           (*PY, "tests/agents/test_agent_runs.py")),
    Mutant("M-AG21", "Agent run: a revoked (tampered) agent can start a run",
           "server/composition/agents.py",
           "        if spec is None:\n            raise await self._refuse_run(audit, principal, agent_id, \"agent_revoked\",\n"
           "                                         \"this agent is revoked and cannot run\")",
           "        if False:\n            raise await self._refuse_run(audit, principal, agent_id, \"agent_revoked\",\n"
           "                                         \"this agent is revoked and cannot run\")",
           (*PY, "tests/agents/test_agent_runs.py")),
    Mutant("M-AG22", "Agent run: a template bump no longer sends a run's spec back for re-approval",
           "server/composition/agents.py",
           "        if revalidation_required(spec, registries.enabled_templates):\n",
           "        if False:\n",
           (*PY, "tests/agents/test_agent_runs.py")),
    Mutant("M-AG23", "Agent run: a model profile no longer configured or permitted still runs",
           "server/composition/agents.py",
           "                or profile.profile.version != selection.model_profile_version\n"
           "                or (profile.profile_id not in registries.open_to_all\n",
           "                or False\n"
           "                or (False\n",
           (*PY, "tests/agents/test_agent_runs.py")),
    Mutant("M-AG24", "Agent run: the spec's own bounds no longer tighten the runtime's",
           "server/agent/runtime.py",
           "        return min(self._bounds.max_model_calls, state.agent.max_model_calls)\n",
           "        return self._bounds.max_model_calls\n",
           (*PY, "tests/agents/test_agent_runs.py")),
    Mutant("M-AG25", "Agent run: a run id is read under an agent it does not belong to",
           "server/composition/agents.py",
           "        if run is None or run.agent_id != agent_id or run.owner_user_id != principal.user_id:\n",
           "        if run is None:\n",
           (*PY, "tests/agents/test_agent_runs.py")),
    Mutant("M-AG26", "Agent run: a model profile the operator disabled still runs",
           "server/composition/agents.py",
           "        if (profile is None or not profile.profile.enabled\n",
           "        if (profile is None or False\n",
           (*PY, "tests/agents/test_agent_runs.py")),
    Mutant("M-AG27", "Envelope gate: a capability outside the agent's envelope can be activated or offered",
           "server/agent/runtime.py",
           "            if not agent_envelope.activation_within_envelope(self._envelope(state), capability, scope):\n",
           "            if False:\n",
           (*PY, "tests/agents/test_envelope_gate.py")),
    Mutant("M-AG28", "Envelope gate: a tool call outside the envelope reaches the engine",
           "server/agent/runtime.py",
           "        if not self._within_envelope(env, state, handle.required_capability, call.operation,\n",
           "        if False and self._within_envelope(env, state, handle.required_capability, call.operation,\n",
           (*PY, "tests/agents/test_envelope_gate.py")),
    Mutant("M-AG29", "Envelope gate: an approved activation is no longer re-checked against the envelope",
           "server/agent/runtime.py",
           "        if not agent_envelope.activation_within_envelope(self._envelope(state), pending.capability,\n",
           "        if False and agent_envelope.activation_within_envelope(self._envelope(state), pending.capability,\n",
           (*PY, "tests/agents/test_envelope_gate.py")),
    Mutant("M-AG30", "Envelope gate: the agent's worker is shown tools outside its envelope",
           "server/agent/runtime.py",
           "            handles = [h for h in handles if h.required_capability in reachable and not h.is_model_tool]\n",
           "            handles = [h for h in handles if not h.is_model_tool]\n",
           (*PY, "tests/agents/test_envelope_gate.py")),
    Mutant("M-AG31", "Envelope gate: an entry's scope no longer bounds the call's scope",
           "server/agent/envelope.py",
           "    return all(scope.get(key) == value for key, value in entry_scope.items())",
           "    return True",
           (*PY, "tests/agents/test_envelope_gate.py")),
    Mutant("M-AG32", "Agent run: an owner removed from the agent's graph keeps running it",
           "server/agents/service.py",
           "        if definition.graph_id is not None and not await is_member(definition.graph_id, run.owner_user_id):\n",
           "        if False:\n",
           (*PY, "tests/agents/test_envelope_gate.py")),
    Mutant("M-AG33", "Envelope gate: agent.*/system.restricted/device names are no longer refused by name",
           "server/agent/envelope.py",
           "    return any(name == n or name.startswith(n) for n in _NEVER)",
           "    return False",
           (*PY, "tests/agents/test_future_interfaces.py", "tests/agents/test_envelope_gate.py")),
    Mutant("M-AG34", "Model routing: a model tool can be called directly in an agent run, around the routing",
           "server/agent/runtime.py",
           "        if state.agent is not None and handle.is_model_tool and not routed:\n",
           "        if False:\n",
           (*PY, "tests/agents/test_model_routing_runs.py")),
    Mutant("M-AG35", "Model routing: agent.model is routed for an agent whose envelope has no model.invoke",
           "server/agent/runtime.py",
           "        if not agent.model_tools:\n            await self._envelope_denied(env, state, resource)\n",
           "        if False:\n            await self._envelope_denied(env, state, resource)\n",
           (*PY, "tests/agents/test_model_routing_runs.py")),
    Mutant("M-AG36", "Model routing: a request naming a provider/model/endpoint/key is accepted (schema bypass)",
           "server/composition/agents.py",
           "            request = ModelCallRequest.model_validate(dict(arguments))\n",
           "            request = ModelCallRequest.model_validate({k: v for k, v in dict(arguments).items() "
           "if k in ModelCallRequest.model_fields})\n",
           (*PY, "tests/agents/test_model_routing_runs.py")),
    Mutant("M-AG37", "Model routing: a profile the owner may not use can be chosen",
           "server/agents/gateway/model_routing.py",
           "        if p.profile_id not in registries.open_to_all and p.model_ref != owner_primary_model_ref:\n",
           "        if False:\n",
           (*PY, "tests/agents/test_future_interfaces.py", "tests/agents/test_model_routing_runs.py")),
    Mutant("M-AG38", "Model routing: a model over the run's budget can be chosen",
           "server/agents/gateway/model_routing.py",
           "        if m.projected_cost(1) > spec.budget.per_run:\n",
           "        if False:\n",
           (*PY, "tests/agents/test_future_interfaces.py", "tests/agents/test_model_routing_runs.py")),
    Mutant("M-AG39", "Model routing: the routed call skips the envelope gate and the engine (routing authorizes)",
           "server/agent/runtime.py",
           "            call, routed = rewritten, True\n            resource = f\"tool:{call.tool}.{call.operation}\"\n",
           "            call, routed = rewritten, True\n            resource = f\"tool:{call.tool}.{call.operation}\"\n"
           "            _h = self._tools.resolve(call.tool)\n"
           "            await self._execute(env, state, _h, call.operation, ExecutionPlatform.SERVER, "
           "dict(call.arguments), None, {\"model_tool_id\": call.tool}, remaining)\n"
           "            return None\n",
           (*PY, "tests/agents/test_model_routing_runs.py")),
    Mutant("M-AG40", "Agent run budget: the agent's per-run budget no longer tightens the task budget",
           "server/agent/runtime.py",
           "        return min(self._bounds.per_task_budget, state.agent.budget_per_run)\n",
           "        return self._bounds.per_task_budget\n",
           (*PY, "tests/agents/test_model_routing_runs.py")),
    Mutant("M-AG41", "Run stop: cancelling a run no longer stops its task (the paused action stays confirmable)",
           "server/composition/agents.py",
           "                await self._tasks.cancel(self._session, principal=self._principal, task_id=run.task_id,\n",
           "                pass; await self._tasks.get(self._session, principal=self._principal, task_id=run.task_id,\n",
           (*PY, "tests/agents/test_run_control.py")),
    # Since Phase 3 a proposed tool call is re-validated by its Tool Gateway
    # admission (token, run, definition — docs/29 §13.3 steps 1–3).
    Mutant("M-AG49", "Agent run: a tool call proposed before a stop/delete/change is not re-validated",
           "server/agent/runtime.py",
           "        admission = await self._admit(env, state, RunTokenPurpose.TOOL, digest)\n",
           "        admission = GatewayAdmission()\n",
           (*PY, "tests/agents/test_run_control.py", "tests/agents/test_gateway_runs.py")),
    Mutant("M-AG42", "Run stop: a cancelled run's record is not closed (its re-validation still passes)",
           "server/composition/agents.py",
           "        await self._service.run_cancelled(self._session, run_id, reason=reason.value)\n",
           "        pass\n",
           (*PY, "tests/agents/test_run_control.py")),
    Mutant("M-AG43", "Pause: pausing an agent leaves its live runs running",
           "server/composition/agents.py",
           "        await self._stop_runs(session, audit, principal, agent_id, CancelReason.OWNER_STOP)\n",
           "        pass\n",
           (*PY, "tests/agents/test_run_control.py")),
    Mutant("M-AG44", "Delete: deleting an agent leaves its live runs running",
           "server/composition/agents.py",
           "            await self._stop_runs(session, audit, principal, agent_id, CancelReason.DELETED)\n",
           "            pass\n",
           (*PY, "tests/agents/test_run_control.py")),
    Mutant("M-AG45", "Delete (service path): a deleted agent's run records stay open",
           "server/agents/service.py",
           "            await self.run_cancelled(session, run.run_id, reason=\"deleted\")\n",
           "            pass\n",
           (*PY, "tests/agents/test_run_control.py")),
    Mutant("M-AG46", "Resume: an agent is resumed without the owner's confirmation",
           "server/composition/agents.py",
           "        await self._confirm_or_refuse(session, outcome, action=\"resume_agent\",\n",
           "        dict(s=session, o=outcome, action=\"resume_agent\",\n",
           (*PY, "tests/agents/test_run_control.py")),
    Mutant("M-AG47", "Resume: an outdated template is resumed without re-approval",
           "server/composition/agents.py",
           "        await self._still_runnable(session, audit, principal, definition, spec)\n        outcome",
           "        outcome",
           (*PY, "tests/agents/test_run_control.py")),
    Mutant("M-AG48", "Run stop: another user can stop a run (owner check removed)",
           "server/composition/agents.py",
           "        run = await self._owned_run(session, audit, principal, agent_id, run_id)\n        service = self._factory.service\n        if run.finished_at is None:",
           "        run = await self._factory.service.get_run(session, run_id)\n        service = self._factory.service\n        if run.finished_at is None:",
           (*PY, "tests/agents/test_run_control.py")),
    Mutant("M-AG50", "Notebook: an agent whose spec does not enable the notebook can use it",
           "server/agent/runtime.py",
           "        if not agent.notebook:\n            await self._envelope_denied(env, state, resource)\n"
           "            state.messages.append(ctx.observation(agent_envelope.not_in_envelope(NOTEBOOK_TOOL),",
           "        if False:\n            await self._envelope_denied(env, state, resource)\n"
           "            state.messages.append(ctx.observation(agent_envelope.not_in_envelope(NOTEBOOK_TOOL),",
           (*PY, "tests/agents/test_notebook.py")),
    Mutant("M-AG51", "Notebook: a credential-shaped note is stored",
           "server/composition/agents.py",
           "        if find_secret(f\"{key}\\n{value}\") is not None:\n",
           "        if False:\n",
           (*PY, "tests/agents/test_notebook.py")),
    Mutant("M-AG52", "Notebook: an emotional/relational note is stored",
           "server/composition/agents.py",
           "        if _EMOTION.flags(f\"{key} {value}\"):\n",
           "        if False:\n",
           (*PY, "tests/agents/test_notebook.py")),
    Mutant("M-AG53", "Notebook: the per-agent entry bound is not enforced",
           "server/agents/service.py",
           "            if count >= NOTEBOOK_MAX_ENTRIES:\n",
           "            if False:\n",
           (*PY, "tests/agents/test_notebook.py")),
    Mutant("M-AG54", "Notebook: deleting the agent leaves its notebook behind",
           "server/agents/service.py",
           "        await self.notebook_clear(session, agent_id)\n        await session.execute(delete(AgentInboxItemRow)",
           "        await session.execute(delete(AgentInboxItemRow)",
           (*PY, "tests/agents/test_notebook.py")),
    Mutant("M-AG55", "Notebook: keys are not validated (path-like or overlong keys are stored)",
           "server/agents/service.py",
           "        if not _NOTEBOOK_KEY.fullmatch(key):\n",
           "        if False:\n",
           (*PY, "tests/agents/test_notebook.py")),
    Mutant("M-AG56", "Notebook: the owner API shows another owner's agent's notebook",
           "server/composition/agents.py",
           "        await self._owned(session, audit, principal, agent_id, Operation.READ)\n"
           "        rows = await self._factory.service.notebook_entries(session, agent_id, principal.user_id)\n",
           "        rows = await self._factory.service.notebook_entries(session, agent_id, principal.user_id)\n",
           (*PY, "tests/agents/test_notebook.py")),
    Mutant("M-AG57", "Inbox: a credential-shaped result is stored and shown",
           "server/composition/agents.py",
           "    if find_secret(text) is not None:\n        return \"\", True, False\n",
           "    if False:\n        return \"\", True, False\n",
           (*PY, "tests/agents/test_inbox.py")),
    Mutant("M-AG58", "Inbox: control characters / terminal escapes reach the owner's client",
           "server/composition/agents.py",
           "    text = _UNSAFE_CHARS.sub(\"\", response or \"\")\n",
           "    text = response or \"\"\n",
           (*PY, "tests/agents/test_inbox.py")),
    Mutant("M-AG59", "Inbox: an item is not bounded",
           "server/composition/agents.py",
           "    if len(text) > INBOX_MAX_BODY_CHARS:\n",
           "    if False:\n",
           (*PY, "tests/agents/test_inbox.py")),
    Mutant("M-AG60", "Inbox: deleting the agent leaves its items behind",
           "server/agents/service.py",
           "        await session.execute(delete(AgentInboxItemRow).where(AgentInboxItemRow.agent_id == agent_id))\n",
           "        pass\n",
           (*PY, "tests/agents/test_inbox.py")),
    # Needs the memory stack: run with HYPERMIND_REQUIRE_MEMORY_STACK=1 (else the test skips).
    Mutant("M-AG61", "Memory: an agent run's output is extracted into the owner's Mem0 memory",
           "server/agent/runtime.py",
           "        if state.agent is not None:\n            # docs/29 §16.2 (AGENT-T17)",
           "        if False:\n            # docs/29 §16.2 (AGENT-T17)",
           (*PY, "tests/memory/test_agent_memory_exclusion.py")),
    Mutant("M-AG62", "Attribution: an agent run's tool calls are not attributed to it",
           "server/agent/runtime.py",
           "        await self._attribute(env, state, usage_id, output.estimated_cost)\n",
           "        pass\n",
           (*PY, "tests/agents/test_attribution_export.py")),
    Mutant("M-AG63", "Attribution: an agent run's model calls are not attributed to it",
           "server/agent/runtime.py",
           "        await self._attribute(env, state, usage_id, cost)\n",
           "        pass\n",
           (*PY, "tests/agents/test_attribution_export.py")),
    Mutant("M-AG64", "Budget: a run starts although the agent's month is spent",
           "server/composition/agents.py",
           "        if spec.budget.per_month > 0 and spent >= spec.budget.per_month:\n",
           "        if False:\n",
           (*PY, "tests/agents/test_attribution_export.py")),
    Mutant("M-AG65", "Budget: a run's ceiling is not capped by what is left of the month",
           "server/composition/agents.py",
           "        run_budget = min(spec.budget.per_run, max(0.0, spec.budget.per_month - spent))\n",
           "        run_budget = spec.budget.per_run\n",
           (*PY, "tests/agents/test_attribution_export.py")),
    Mutant("M-AG66", "Export: another user can export an agent (owner check removed)",
           "server/composition/agents.py",
           "        definition, spec = await self._owned(session, audit, principal, agent_id, Operation.READ)\n"
           "        service = self._factory.service\n        port = _PresentUserRun(",
           "        definition, spec = await self._factory.service.load(session, agent_id)\n"
           "        service = self._factory.service\n        port = _PresentUserRun(",
           (*PY, "tests/agents/test_attribution_export.py")),
    Mutant("M-AG67", "Agent run: inside the envelope an activation needs no owner grant (envelope treated as a grant)",
           "server/agent/runtime.py",
           "            if await env.security.holds_standing_grant(\n",
           "            if state.agent is not None or await env.security.holds_standing_grant(\n",
           (*PY, "tests/agents/test_envelope_gate.py", "tests/agents/test_model_routing_runs.py")),
    Mutant("M-AG68", "Agent run: an authorization decision is cached and reused (revocation no longer applies)",
           "server/agent/runtime.py",
           "        verdict = await env.security.authorize_action(request)\n",
           "        _cache = state.__dict__.setdefault(\"_authz_cache\", {})\n"
           "        _key = (handle.required_capability, call.operation)\n"
           "        verdict = _cache.get(_key) or await env.security.authorize_action(request)\n"
           "        _cache[_key] = verdict\n",
           (*PY, "tests/agents/test_envelope_gate.py", "tests/agents/test_model_routing_runs.py")),
    Mutant("M-AG69", "Envelope gate: an operation above the template's risk ceiling passes",
           "server/agent/envelope.py",
           "    if risk_severity(tier) > risk_severity(envelope.risk_ceiling):\n",
           "    if False:\n",
           (*PY, "tests/agents/test_future_interfaces.py", "tests/agents/test_envelope_gate.py")),
    # ── docs/29 Phase 3, slice 3A: run tokens, nonces, the gateway's check ──
    Mutant("M-AG6", "Run token: a revoked token is still accepted (revoked_at ignored)",
           "server/agents/gateway/tokens.py",
           "    if facts.revoked_at is not None:\n        return \"revoked\"",
           "    if False:\n        return \"revoked\"",
           (*PY, "tests/agents/test_gateway_tokens.py", "tests/agents/test_gateway_runs.py")),
    Mutant("M-AG7", "Run token: the token is no longer bound to its run's spec hash",
           "server/agents/gateway/tokens.py",
           "    if run_spec_hash is None or facts.spec_hash != run_spec_hash:\n        return \"binding\"",
           "    if False:\n        return \"binding\"",
           (*PY, "tests/agents/test_gateway_tokens.py")),
    Mutant("M-AG8", "Gateway: a nonce reused for a different request is not a replay",
           "server/agents/gateway/core.py",
           "            if seen.request_digest != request.request_digest:\n",
           "            if False:\n",
           (*PY, "tests/agents/test_gateway_tokens.py", "tests/agents/test_gateway_runs.py")),
    Mutant("M-AG70", "Gateway: a stale request (sent_at outside the window) is admitted",
           "server/agents/gateway/core.py",
           "        if not run_tokens.is_fresh(_utc(request.sent_at), self.now()):\n",
           "        if False:\n",
           (*PY, "tests/agents/test_gateway_tokens.py", "tests/agents/test_gateway_runs.py")),
    Mutant("M-AG71", "Run token: token validation skipped (any presented token passes the binding check)",
           "server/agents/gateway/tokens.py",
           "    `None` if so, else why not (`unknown`, `purpose`, `binding`).\"\"\"\n\n",
           "    `None` if so, else why not (`unknown`, `purpose`, `binding`).\"\"\"\n    return None\n",
           (*PY, "tests/agents/test_gateway_tokens.py")),
    Mutant("M-AG72", "Run token: an expired token is still accepted",
           "server/agents/gateway/tokens.py",
           "    if now >= facts.expires_at:\n",
           "    if False:\n",
           (*PY, "tests/agents/test_gateway_tokens.py", "tests/agents/test_gateway_runs.py")),
    Mutant("M-AG73", "Run token: a token is accepted by the other gateway (purpose ignored)",
           "server/agents/gateway/tokens.py",
           "    if facts.purpose != purpose.value:\n",
           "    if False:\n",
           (*PY, "tests/agents/test_gateway_tokens.py")),
    Mutant("M-AG74", "Run token: a token is accepted for another run or agent (binding ignored)",
           "server/agents/gateway/tokens.py",
           "    if facts.run_id != run_id or facts.agent_id != agent_id:\n",
           "    if False:\n",
           (*PY, "tests/agents/test_gateway_tokens.py")),
    Mutant("M-AG75", "Gateway: a retried request is executed again instead of answered from the ledger",
           "server/agents/gateway/core.py",
           "            return GatewayReplayed(context=context, response=dict(seen.response))\n",
           "            return GatewayAdmitted(context=context, nonce=request.request_nonce)\n",
           (*PY, "tests/agents/test_gateway_tokens.py")),
    Mutant("M-AG76", "Runtime: a replayed tool request is performed again",
           "server/agent/runtime.py",
           "        if admission.replayed is not None:\n            # A retry of a request already answered",
           "        if False:\n            # A retry of a request already answered",
           (*PY, "tests/agents/test_gateway_runs.py")),
    Mutant("M-AG77", "Stop: a cancelled run's tokens are revoked only after the runtime was told (AGENT-T23)",
           "server/composition/agents.py",
           "        if await self._gateway.revoke_run(self._session, run_id, reason.value):\n",
           "        if False:\n",
           (*PY, "tests/agents/test_gateway_runs.py")),
    Mutant("M-AG78", "Run token: the token is stored in the clear instead of its hash",
           "server/agents/gateway/tokens.py",
           "    return hashlib.sha256(token.encode(\"utf-8\")).hexdigest()\n",
           "    return token\n",
           (*PY, "tests/agents/test_gateway_tokens.py", "tests/agents/test_gateway_runs.py")),
    Mutant("M-AG79", "Run token: a finished or cancelled run's tokens stay valid",
           "server/agents/service.py",
           "        await self.revoke_run_tokens(session, run_id, revoke_reason)\n",
           "        pass\n",
           (*PY, "tests/agents/test_gateway_tokens.py")),
    # ── docs/29 Phase 3, slice 3B: the Model Gateway ─────────────────────
    Mutant("M-AG80", "Model Gateway: the alias/profile/policy screen is skipped (any model call admitted)",
           "server/composition/agents.py",
           "        return GatewayDenied(not_allowed, refused) if refused is not None else None\n",
           "        return None\n",
           (*PY, "tests/agents/test_model_gateway.py")),
    Mutant("M-AG81", "Model Gateway: the owner's current model policy is not re-checked at each call",
           "server/agents/gateway/model_gateway.py",
           "    if profile.profile_id not in registries.open_to_all and profile.model_ref != owner_primary_model_ref:\n",
           "    if False:\n",
           (*PY, "tests/agents/test_model_gateway.py")),
    Mutant("M-AG82", "Model Gateway: a call to another provider or model than the approved profile's is admitted",
           "server/agents/gateway/model_gateway.py",
           "    if (provider, model) != (None, None) and (provider, model) != (resolved.provider, resolved.model):\n",
           "    if False:\n",
           (*PY, "tests/agents/test_model_gateway.py")),
    Mutant("M-AG83", "Model Gateway: a model tool is admitted without model.invoke in the envelope",
           "server/agents/gateway/model_gateway.py",
           "        if not invoke or (pinned and tool_id not in pinned):\n",
           "        if False:\n",
           (*PY, "tests/agents/test_model_gateway.py")),
    Mutant("M-AG84", "Model Gateway: the agent's month is not checked at each paid call",
           "server/agent/runtime.py",
           "            refused = await env.agent_runs.agent_budget(state.agent, projected_cost=projected)\n",
           "            refused = None\n",
           (*PY, "tests/agents/test_model_gateway.py")),
    Mutant("M-AG85", "Model Gateway: the month's spend ignores the agent's live (concurrent) runs",
           "server/agents/service.py",
           "        return await self.month_spend(session, agent_id, now) + float(live or 0.0)\n",
           "        return await self.month_spend(session, agent_id, now)\n",
           (*PY, "tests/agents/test_model_gateway.py")),
    Mutant("M-AG86", "Model Gateway: a routed (model-as-tool) call is not a Model Gateway request",
           "server/agent/runtime.py",
           "        if routed:\n            # docs/29 §12: a model reached as a tool",
           "        if False:\n            # docs/29 §12: a model reached as a tool",
           (*PY, "tests/agents/test_model_gateway.py")),
    Mutant("M-AG87", "Model Gateway: the run's own model calls bypass the Model Gateway",
           "server/agent/runtime.py",
           "        if state.agent is not None:\n            # docs/29 §12: an agent run's model call is a request",
           "        if False:\n            # docs/29 §12: an agent run's model call is a request",
           (*PY, "tests/agents/test_model_gateway.py", "tests/agents/test_gateway_runs.py")),
    Mutant("M-AG88", "Model Gateway: the month check ignores the call's own projected cost",
           "server/agents/gateway/model_gateway.py",
           "    if month_spent + projected_cost > month_budget:\n",
           "    if month_spent > month_budget:\n",
           (*PY, "tests/agents/test_model_gateway.py")),
    # docs/29 §18, §23.2, §14.3 (Phase 3, slice 3C): the Judge, the console and the operator's pause.
    Mutant("M-AG89", "Judge authority: a superuser approval applies an owner-scoped (agent.purpose) candidate",
           "server/composition/improvements.py",
           "        if row.target in OWNER_SCOPED_TARGETS:\n",
           "        if False:\n",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG90", "Judge authority: an agent's authority (agent.*) is no longer a forbidden target",
           "server/evaluation/candidates.py",
           "    \"agent\": \"agent_authority\",\n",
           "",
           (*PY, "tests/evaluation/test_judge_contract.py", "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG91", "Judge authority: an agent.purpose candidate is accepted from a task that is no agent run",
           "server/evaluation/candidates.py",
           "    if target in OWNER_SCOPED_TARGETS and not agent_run:\n",
           "    if False:\n",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG92", "Judge attribution: the runtime's snapshot drops the run's agent",
           "server/agent/runtime.py",
           "            agent_id=state.agent.agent_id if state.agent is not None else None,\n",
           "            agent_id=None,\n",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG93", "Judge attribution: an owner-scoped candidate is stored without its agent",
           "server/composition/evaluation.py",
           "agent_id=record.agent_id if accepted.target in OWNER_SCOPED_TARGETS else None,",
           "agent_id=None,",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG94", "Purpose candidate: a recompile that changes more than the purpose is offered",
           "server/composition/agents.py",
           "        if preview is None or authority_of(service.preview_spec(preview)) != authority_of(spec):\n",
           "        if preview is None:\n",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG95", "Purpose candidate: decided through another agent's URL",
           "server/composition/agents.py",
           "        if row is None or row.agent_id != agent_id or row.source_user_id != principal.user_id:\n",
           "        if row is None or row.source_user_id != principal.user_id:\n",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG96", "Agent delete: the Judge's suggestions for the agent survive it",
           "server/agents/service.py",
           "        await session.execute(delete(ImprovementCandidateRow).where(\n",
           "        (lambda *_: None)(delete(ImprovementCandidateRow).where(\n",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG97", "Operator pause: the owner resumes past the operator's hold",
           "server/composition/agents.py",
           "        if definition.status_reason == OPERATOR_PAUSED:\n            # docs/29 §14.3: the operator's pause holds until",
           "        if False:\n            # docs/29 §14.3: the operator's pause holds until",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG98", "Operator pause: the hold is not re-read after the engine's decision on a resume",
           "server/composition/agents.py",
           "        if definition.status_reason == OPERATOR_PAUSED:\n            # Re-read after the engine's decision",
           "        if False:\n            # Re-read after the engine's decision",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG99", "Operator pause: the agent's live runs are not tripped",
           "server/composition/supervisor.py",
           "            [s for s in self._runtime.states.live() if s.agent is not None and s.agent.agent_id == agent_id],\n",
           "            [],\n",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG100", "Operator pause: the agent's run tokens are not revoked",
           "server/agents/service.py",
           "        revoked = await self.revoke_agent_tokens(session, definition.agent_id, OPERATOR_PAUSED)\n",
           "        revoked = 0\n",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG101", "Operator pause: an agent awaiting re-approval escapes the hold",
           "server/agents/service.py",
           "        if definition.status in _LIVE:\n            definition.status = AgentStatus.PAUSED.value\n",
           "        if definition.status in (AgentStatus.ACTIVE.value, AgentStatus.PAUSED.value):\n"
           "            definition.status = AgentStatus.PAUSED.value\n",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    Mutant("M-AG102", "Console: an agent's name (user content) is shown unredacted",
           "server/dashboard/console.py",
           "\"name\": redact_user_text(row.name),",
           "\"name\": row.name,",
           (*PY, "tests/agents/test_agent_judge_console.py")),
    # docs/29 §17 (Phase 4, slice 4A): an agent's reminder is an ordinary job; firing never executes.
    Mutant("M-AG103", "Scheduler: the scheduler gains a path to the Agent Factory (a way to start an agent)",
           "server/scheduler/service.py",
           "from __future__ import annotations\n",
           "from __future__ import annotations\n\nimport server.agents.service  # noqa: F401 — mutant\n",
           ("lint-imports", "--config", "pyproject.toml")),
    Mutant("M-AG104", "Scheduler firing: an agent reminder loses its agent (the client cannot offer the run)",
           "server/scheduler/firing.py",
           "                agent_id=job.agent_id,\n",
           "",
           (*PY, "tests/agents/test_agent_reminders.py")),
    Mutant("M-AG105", "Reminder frame: agent_id reaches a client that never declared agent_reminders",
           "shared/schemas/device_channel.py",
           "        exclude = None if (self.agent_id is not None and agent_reminders) else {\"agent_id\"}\n",
           "        exclude = None if self.agent_id is not None else {\"agent_id\"}\n",
           (*PY, "tests/agents/test_agent_reminders.py")),
    Mutant("M-AG106", "Reminder frame: a plain reminder carries a null agent_id",
           "shared/schemas/device_channel.py",
           "        exclude = None if (self.agent_id is not None and agent_reminders) else {\"agent_id\"}\n",
           "        exclude = None if agent_reminders else {\"agent_id\"}\n",
           (*PY, "tests/agents/test_agent_reminders.py")),
    Mutant("M-AG107", "Agent pause: a paused agent's reminder keeps firing",
           "server/composition/agents.py",
           "        # docs/29 §14.1 / §17.1: a paused agent's reminder is suppressed.\n"
           "        await self._unschedule(session, audit, principal, agent_id)\n",
           "        # docs/29 §14.1 / §17.1: a paused agent's reminder is suppressed.\n",
           (*PY, "tests/agents/test_agent_reminders.py")),
    Mutant("M-AG108", "Agent delete: a deleted agent's reminder keeps firing",
           "server/composition/agents.py",
           "        await self._unschedule(session, audit, principal, agent_id)\n"
           "        await self._factory.service.delete(session, loaded[0])\n",
           "        await self._factory.service.delete(session, loaded[0])\n",
           (*PY, "tests/agents/test_agent_reminders.py")),
    Mutant("M-AG109", "Agent update: the old reminder survives the new version",
           "server/composition/agents.py",
           "        # docs/29 §17.1: the reminder follows the new version (or goes).\n"
           "        await self._unschedule(session, audit, principal, agent_id)\n",
           "        # docs/29 §17.1: the reminder follows the new version (or goes).\n",
           (*PY, "tests/agents/test_agent_reminders.py")),
    Mutant("M-AG110", "Operator pause: the agent's reminder keeps firing",
           "server/composition/supervisor.py",
           "            await self._agents.reminders.cancel(session, audit, agent_id=agent_id,\n",
           "            (lambda *_, **__: None)(session, audit, agent_id=agent_id,\n",
           (*PY, "tests/agents/test_agent_reminders.py")),
    Mutant("M-AG111", "Agent reminder: the scheduler's per-user quota is skipped",
           "server/composition/agents.py",
           "        if not await self._has_active(session, spec.agent_id, spec.owner_user_id):\n",
           "        if False:\n",
           (*PY, "tests/agents/test_agent_reminders.py")),
    Mutant("M-AG112", "Agent reminder: the one engine is not consulted for the scheduled job",
           "server/composition/agents.py",
           "            graph_id=spec.graph_id), audit=audit)\n        if not outcome.allowed:\n            raise _refusal(outcome)\n        return prepared\n",
           "            graph_id=spec.graph_id), audit=audit)\n        return prepared\n",
           (*PY, "tests/agents/test_agent_reminders.py")),
    # docs/29 §17.1 (Phase 4, slice 4B): the reminder tap is the present owner's ordinary run.
    Mutant("M-AG113", "Reminder tap: a reminder delivered to another device starts a run",
           "server/composition/agents.py",
           "                or delivery.user_id != principal.user_id or delivery.device_id != principal.device_id\n",
           "                or delivery.user_id != principal.user_id\n",
           (*PY, "tests/agents/test_reminder_tap.py")),
    Mutant("M-AG114", "Reminder tap: one agent's reminder starts another agent's run",
           "server/composition/agents.py",
           "                or job.owner_user_id != principal.user_id or job.agent_id != agent_id):\n",
           "                or job.owner_user_id != principal.user_id):\n",
           (*PY, "tests/agents/test_reminder_tap.py")),
    Mutant("M-AG115", "Reminder tap: a reminder the device was never sent counts as a tap",
           "server/composition/agents.py",
           "        if (delivery is None or job is None or delivery.status not in _RECEIVED\n",
           "        if (delivery is None or job is None\n",
           (*PY, "tests/agents/test_reminder_tap.py")),
    Mutant("M-AG116", "Reminder tap: a repeated tap is decided afresh instead of answered with its run",
           "server/composition/agents.py",
           "            if tapped is not None:\n                # The same tap again (a double tap, a retry after no answer):\n",
           "            if False:\n                # The same tap again (a double tap, a retry after no answer):\n",
           (*PY, "tests/agents/test_reminder_tap.py")),
    Mutant("M-AG117", "Reminder tap: two racing taps fail instead of sharing one run",
           "server/composition/agents.py",
           "        except IntegrityError:\n",
           "        except ZeroDivisionError:\n",
           (*PY, "tests/agents/test_reminder_tap.py")),
    Mutant("M-AG118", "Reminder tap: a tapped run is recorded as on demand",
           "server/agents/service.py",
           "                          kind=\"reminder_tap\" if reminder_delivery_id is not None else \"on_demand\",\n",
           "                          kind=\"on_demand\",\n",
           (*PY, "tests/agents/test_reminder_tap.py")),
    Mutant("M-AG119", "Android: a run the server refused is shown as if it ran (server authority bypassed)",
           "android/contract/src/main/kotlin/com/hypermind/jarvis/contract/Agents.kt",
           "            if (httpStatus !in SUCCESS) {\n                TaskView.Failed(null, errorCode(",
           "            if (false) {\n                TaskView.Failed(null, errorCode(",
           tuple(GRADLE), cwd="android"),
    Mutant("M-AG120", "Android: an agent reminder's agent id is taken unvalidated",
           "android/contract/src/main/kotlin/com/hypermind/jarvis/contract/Reminders.kt",
           "        require(agentId == null || UUID_FORM.matches(agentId)) { \"agent id malformed\" }\n",
           "",
           tuple(GRADLE), cwd="android"),
    Mutant("M-AG121", "Android: a run offer is made for a reminder that named no agent",
           "android/app/src/main/kotlin/com/hypermind/jarvis/reminders/ReminderDrafts.kt",
           "            val agentId = drafts.agentFor(deliveryId) ?: return null\n",
           "            val agentId = drafts.agentFor(deliveryId) ?: deliveryId\n",
           ("./gradlew", "--offline", "-q", ":app:testDebugUnitTest", "--tests", "com.hypermind.jarvis.reminders.*", "--tests", "com.hypermind.jarvis.tasks.TaskTrackerTest"), cwd="android"),
    Mutant("M-AG122", "Android: an on-demand run is sent again after a lost answer (could run twice)",
           "android/app/src/main/kotlin/com/hypermind/jarvis/tasks/TaskTracker.kt",
           "        unansweredTap = reminderDeliveryId?.let { agentId to it }\n",
           "        unansweredTap = agentId to (reminderDeliveryId ?: \"\")\n",
           ("./gradlew", "--offline", "-q", ":app:testDebugUnitTest", "--tests", "com.hypermind.jarvis.reminders.*", "--tests", "com.hypermind.jarvis.tasks.TaskTrackerTest"), cwd="android"),
    Mutant("M-AG3", "Agent selector: a runtime the operator did not enable can be selected",
           "server/agents/selector.py",
           "        if not runtime.enabled:\n",
           "        if False:\n",
           (*PY, "tests/agents/test_selector.py")),
    Mutant("M-AG4", "Agent selector: a runtime below the template's minimum isolation can be selected",
           "server/agents/selector.py",
           "        if ISOLATION_ORDER[runtime.isolation_mode] < ISOLATION_ORDER[template.min_isolation]:",
           "        if False:",
           (*PY, "tests/agents/test_selector.py")),
    Mutant("M-AG5", "Agent compiler: a never-mappable capability (agent.*, system.restricted, device.*) reaches an envelope",
           "server/agents/compiler.py",
           "        if abilities.never_mappable(mapping.capability):\n            return None, [\"never_mappable\"]",
           "        if False:\n            return None, [\"never_mappable\"]",
           (*PY, "tests/agents/test_compiler.py")),
    Mutant("M-AG13", "Agent revalidation: a template version bump no longer sends older specs through revalidation",
           "server/agents/compiler.py",
           "    return current is None or spec.template_version < current.version",
           "    return current is None or spec.template_version > current.version",
           (*PY, "tests/agents/test_compiler.py")),
    Mutant("M-AG14", "Agent store: a spec altered at rest is loaded without verifying its hash",
           "server/agents/service.py",
           "            verify_spec_hash(spec)\n            and spec.spec_hash == row.spec_hash\n",
           "            True\n            and spec.spec_hash == row.spec_hash\n",
           (*PY, "tests/agents/test_service.py")),
)


def anchor_count(mutant: Mutant) -> int:
    return (ROOT / mutant.path).read_text().count(mutant.old)


def _verdict(mutant: Mutant, done: subprocess.CompletedProcess) -> str:
    """Killed means *the defending tests failed* — not that something else went
    wrong. A collection error, a compile error or an empty selection is
    reported as such, never counted as a kill."""

    output = done.stdout + done.stderr
    if done.returncode == 0:
        return "SURVIVED"
    tool = mutant.command[0]
    if tool == "lint-imports":
        return "killed" if "BROKEN" in output else f"ERROR rc={done.returncode}"
    if tool == "./gradlew":
        failed_test = "FAILED" in output and ("Test" in output or "tests completed" in output)
        return "killed" if failed_test and "Compilation error" not in output else f"ERROR rc={done.returncode}"
    return "killed" if done.returncode == 1 else f"ERROR rc={done.returncode}"


def run(mutant: Mutant) -> tuple[str, float]:
    path = ROOT / mutant.path
    original = path.read_bytes()
    text = original.decode()
    if text.count(mutant.old) != 1:
        return "ANCHOR MISSING", 0.0
    started = time.monotonic()
    try:
        path.write_text(text.replace(mutant.old, mutant.new, 1))
        env = {**os.environ, "HYPERMIND_REQUIRE_MEMORY_STACK": os.environ.get("HYPERMIND_REQUIRE_MEMORY_STACK", "1")}
        done = subprocess.run(list(mutant.command), cwd=ROOT / mutant.cwd, capture_output=True, text=True,
                              env=env, timeout=1800)
        verdict = _verdict(mutant, done)
    except subprocess.TimeoutExpired:
        verdict = "killed (timeout)"
    finally:
        path.write_bytes(original)
    return verdict, time.monotonic() - started


def main(argv: list[str]) -> int:
    if "--list" in argv:
        for m in MUTANTS:
            print(f"{m.id}  {m.guard}  [{m.path}]")
        return 0
    chosen = [m for m in MUTANTS if not argv or m.id in argv]
    survivors = 0
    for m in chosen:
        verdict, seconds = run(m)
        if not verdict.startswith("killed"):
            survivors += 1
        print(f"{m.id}  {verdict:<16} {seconds:6.1f}s  {m.guard}", flush=True)
    print(f"{len(chosen) - survivors}/{len(chosen)} mutants killed")
    return 1 if survivors else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
