"""security-core tables: secret store, oidc login state, tokens, confirmations, access requests

Revision ID: 1a8103630d99
Revises: 3c70e1c8d82a
Create Date: 2026-09-22 02:06:28.975357

Adds the protocol/security-infrastructure tables the mechanisms in `03`, `07`,
and `12` need. `01_DATA_MODEL_SCHEMA.md` enumerates Track B's *entities*, not
these — the same reasoning foundation recorded for `idempotency_keys`. Each
table's purpose and the locked requirement behind it are documented on its ORM
model in `server/storage/models.py`.

No existing table is altered and no column is dropped, so this migration is
additive over foundation's schema: `secret_references` in particular keeps
exactly the shape `01` §8 defines, including having no column capable of holding
a secret value (asserted by
`tests/foundation/test_storage.py::test_secret_reference_table_has_no_value_column`).
The SecretStore's AEAD ciphertext lives in the separate `secret_material` table,
and the key that decrypts it is never in this database (12 §3).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8103630d99'
down_revision: Union[str, Sequence[str], None] = '3c70e1c8d82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_login_states',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('code_verifier', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('secret_store_keys',
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=False),
    sa.Column('wrap_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_table('bootstrap_tokens',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('secret_material',
    sa.Column('secret_ref', sa.String(), nullable=False),
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['secret_store_keys.key_id'], ),
    sa.ForeignKeyConstraint(['secret_ref'], ['secret_references.secret_ref'], ),
    sa.PrimaryKeyConstraint('secret_ref')
    )
    op.create_table('device_proof_nonces',
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_table('graph_access_requests',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.graph_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('uq_graph_access_requests_pending', 'graph_access_requests', ['graph_id', 'user_id'], unique=True, sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
    op.create_table('access_tokens',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index('ix_access_tokens_session_id', 'access_tokens', ['session_id'], unique=False)
    op.create_table('confirmation_tokens',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('principal_user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('capability', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_ref', sa.String(), nullable=True),
    sa.Column('arguments_hash', sa.String(), nullable=False),
    sa.Column('risk_category', sa.Enum('low_read', 'low_write', 'consequential', 'high_irreversible', name='confirmation_risk_category', native_enum=False), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['principal_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index('ix_confirmation_tokens_principal', 'confirmation_tokens', ['principal_user_id', 'task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_confirmation_tokens_principal', table_name='confirmation_tokens')
    op.drop_table('confirmation_tokens')
    op.drop_index('ix_access_tokens_session_id', table_name='access_tokens')
    op.drop_table('access_tokens')
    op.drop_index('uq_graph_access_requests_pending', table_name='graph_access_requests', sqlite_where=sa.text("status = 'pending'"), postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('graph_access_requests')
    op.drop_table('device_proof_nonces')
    op.drop_table('secret_material')
    op.drop_table('bootstrap_tokens')
    op.drop_table('secret_store_keys')
    op.drop_table('oidc_login_states')
    # ### end Alembic commands ###
