"""initial schema

Revision ID: 3c70e1c8d82a
Revises: 
Create Date: 2026-09-22 01:17:08.164844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c70e1c8d82a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configurations',
    sa.Column('config_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.Enum('user', 'graph', name='agentconfig_scope_type', native_enum=False), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=False),
    sa.Column('primary_model', sa.JSON(), nullable=False),
    sa.Column('model_tools', sa.JSON(), nullable=True),
    sa.Column('enabled_tools', sa.JSON(), nullable=True),
    sa.Column('granted_capabilities', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index('uq_agent_configurations_scope', 'agent_configurations', ['scope_type', 'scope_id'], unique=True)
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('request_fingerprint', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('permission_decisions',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('resource_ref', sa.String(), nullable=False),
    sa.Column('decision', sa.Enum('allow', 'deny', 'require_confirmation', name='permission_decision_value', native_enum=False), nullable=False),
    sa.Column('risk_category', sa.Enum('low_read', 'low_write', 'consequential', 'high_irreversible', name='risk_category', native_enum=False), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index('ix_permission_decisions_principal_id', 'permission_decisions', ['principal_id'], unique=False)
    op.create_index('ix_permission_decisions_request_id', 'permission_decisions', ['request_id'], unique=False)
    op.create_table('secret_references',
    sa.Column('secret_ref', sa.String(), nullable=False),
    sa.Column('owner_scope_type', sa.Enum('user', 'graph', 'server', name='secret_owner_scope_type', native_enum=False), nullable=False),
    sa.Column('owner_scope_id', sa.String(), nullable=True),
    sa.Column('class', sa.Enum('model_api_key', 'oauth_token', 'device_credential', 'master_key', 'other', name='secret_class', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('secret_ref')
    )
    op.create_index('ix_secret_references_owner', 'secret_references', ['owner_scope_type', 'owner_scope_id'], unique=False)
    op.create_table('speaker_contexts',
    sa.Column('speaker_context_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('utterance', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_authorization_signal', sa.Boolean(), nullable=False),
    sa.CheckConstraint('is_authorization_signal = 0', name='ck_speaker_contexts_never_auth_signal'),
    sa.PrimaryKeyConstraint('speaker_context_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('oidc_subject', sa.String(), nullable=False),
    sa.Column('oidc_issuer', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='user_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_users_issuer_subject', 'users', ['oidc_issuer', 'oidc_subject'], unique=True)
    op.create_table('capability_grants',
    sa.Column('grant_id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.Enum('user', 'graph', 'device', 'session', 'task', name='capability_scope_type', native_enum=False), nullable=False),
    sa.Column('capability', sa.String(), nullable=False),
    sa.Column('resource_scope', sa.JSON(), nullable=True),
    sa.Column('granted_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('grant_id')
    )
    op.create_index('ix_capability_grants_principal', 'capability_grants', ['principal_id', 'scope_type', 'capability'], unique=False)
    op.create_table('devices',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('android', name='device_platform', native_enum=False), nullable=False),
    sa.Column('credential_ref', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index('ix_devices_user_id', 'devices', ['user_id'], unique=False)
    op.create_table('graphs',
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('private', 'shared', name='graph_type', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('graph_id')
    )
    op.create_index('ix_graphs_owner_user_id', 'graphs', ['owner_user_id'], unique=False)
    op.create_table('file_resources',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('source_user_id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'graph', name='file_visibility', native_enum=False), nullable=False),
    sa.Column('sandbox_root', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_file_resources_size_nonneg'),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.graph_id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('ix_file_resources_graph_owner', 'file_resources', ['graph_id', 'owner_user_id'], unique=False)
    op.create_index('uq_file_resources_root_path', 'file_resources', ['sandbox_root', 'relative_path'], unique=True)
    op.create_table('graph_memberships',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='membership_role', native_enum=False), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.graph_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_index('ix_graph_memberships_user_id', 'graph_memberships', ['user_id'], unique=False)
    op.create_index('uq_graph_memberships_active', 'graph_memberships', ['graph_id', 'user_id'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('scheduled_jobs',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('source_user_id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'graph', name='job_visibility', native_enum=False), nullable=False),
    sa.Column('task_reason', sa.String(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'fired', name='job_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(trim(task_reason)) > 0', name='ck_scheduled_jobs_reason_nonempty'),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.graph_id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_scheduled_jobs_owner_status', 'scheduled_jobs', ['owner_user_id', 'status'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('active_graph_id', sa.Uuid(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['active_graph_id'], ['graphs.graph_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_sessions_device_id', 'sessions', ['device_id'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('graph_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.Enum('user', 'agent', 'tool', 'system', 'superuser', name='audit_actor', native_enum=False), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('decision', sa.Enum('allow', 'deny', 'require_confirmation', name='audit_decision', native_enum=False), nullable=True),
    sa.Column('result', sa.Enum('success', 'failure', 'blocked', name='audit_result', native_enum=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.graph_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_audit_events_graph_timestamp', 'audit_events', ['graph_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_events_request_id', 'audit_events', ['request_id'], unique=False)
    op.create_index('ix_audit_events_user_timestamp', 'audit_events', ['user_id', 'timestamp'], unique=False)
    op.create_table('usage_events',
    sa.Column('usage_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('graph_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('model_call', 'tool_call', name='usage_kind', native_enum=False), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('tool_id', sa.String(), nullable=True),
    sa.Column('tokens_or_units', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('estimated_cost >= 0', name='ck_usage_events_cost_nonneg'),
    sa.CheckConstraint('tokens_or_units >= 0', name='ck_usage_events_tokens_nonneg'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.graph_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_index('ix_usage_events_graph_timestamp', 'usage_events', ['graph_id', 'timestamp'], unique=False)
    op.create_index('ix_usage_events_user_timestamp', 'usage_events', ['user_id', 'timestamp'], unique=False)
    op.create_table('voice_events',
    sa.Column('voice_event_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=False),
    sa.Column('audio_retained', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('voice_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_events')
    op.drop_index('ix_usage_events_user_timestamp', table_name='usage_events')
    op.drop_index('ix_usage_events_graph_timestamp', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index('ix_audit_events_user_timestamp', table_name='audit_events')
    op.drop_index('ix_audit_events_request_id', table_name='audit_events')
    op.drop_index('ix_audit_events_graph_timestamp', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_device_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_scheduled_jobs_owner_status', table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index('uq_graph_memberships_active', table_name='graph_memberships', sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_graph_memberships_user_id', table_name='graph_memberships')
    op.drop_table('graph_memberships')
    op.drop_index('uq_file_resources_root_path', table_name='file_resources')
    op.drop_index('ix_file_resources_graph_owner', table_name='file_resources')
    op.drop_table('file_resources')
    op.drop_index('ix_graphs_owner_user_id', table_name='graphs')
    op.drop_table('graphs')
    op.drop_index('ix_devices_user_id', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_capability_grants_principal', table_name='capability_grants')
    op.drop_table('capability_grants')
    op.drop_index('ix_users_issuer_subject', table_name='users')
    op.drop_table('users')
    op.drop_table('speaker_contexts')
    op.drop_index('ix_secret_references_owner', table_name='secret_references')
    op.drop_table('secret_references')
    op.drop_index('ix_permission_decisions_request_id', table_name='permission_decisions')
    op.drop_index('ix_permission_decisions_principal_id', table_name='permission_decisions')
    op.drop_table('permission_decisions')
    op.drop_table('idempotency_keys')
    op.drop_index('uq_agent_configurations_scope', table_name='agent_configurations')
    op.drop_table('agent_configurations')
    # ### end Alembic commands ###
